### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by GNSPS** [miguelmota/solidity-idiosyncrasies#3]
Hey Miguel, I just stumbled upon this awesome repo. Congrats on putting this together.

About the string comparison:
```
Can't compare two strings; one workaround is to compare the sha3 hashes of the strings.
```

I've seen you mentioned string-utils from Nick Johnson but his assembly code will soon-ish not compile anymore (since it makes use of jump/jumpi instructions which will be deprecated).

Also I'll do a shameless plug here and say that my version of the `bytes` arrays handling lib outperforms comparison with the `keccak256` function for strings both in memory or in storage. 😄 

https://github.com/GNSPS/solidity-bytes-utils/blob/master/contracts/BytesLib.sol#L286
&
https://github.com/GNSPS/solidity-bytes-utils/blob/master/contracts/BytesLib.sol#L329

**Comment by miguelmota** [comment]
@GNSPS good to know! Mentioned your library in the readme

Thanks for the info!
